### ISSUE TITLE
Pihole client names

### ISSUE THREAD

**Issue by deepika05** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#15]
thanks for this guide. How do i get pihole to show various client names in the query log? i followed option A and every query is showing as from localhost. thanks!

**Comment by rajannpatel** [comment]
If you used Option A, your first VPN client profile has an IP address of `fd42:42:42::2`. You can go to `http://[fd42:42:42::1]/admin/network.php` and add a name for your device under **Domain:** and paste `fd42:42:42::2` in the **IP Address:** field.

Let me know if this resolves your question, otherwise I will close the ticket after some days.

**Comment by deepika05** [comment]
i dont have that option under network.php. i ended up editing the /etc/hosts file which worked
