### ISSUE TITLE
Full Tunnel doesnt work but Split is fine

### ISSUE THREAD

**Issue by orchunchun** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#30]
All of a sudden the full tunnel doesnt work, i cant access the internet. Split tunnel still works fine without any issue. 

Tested it by changing the allowed ip on the profile, also on different devices.

**Comment by rajannpatel** [comment]
Was it ever working in the past? Not sure how long ago you followed the guide, but some changes regarding explicitly defining the MTU size in the client config, was a workaround the make full tunnel work.

**Comment by tiagojofran** [comment]
Hi, I have a similar issue now. 
So, I managed to make all this work on oracle cloud, just making a few changes where needed, and all worked perfectly fine for a while, be it split or full tunnel VPN. But then one day, when I upgraded the server from ubuntu 20.01 to 22.01, I just suddenly lost the full tunnel functionality for the VPN, even though split tunnel still works without issues.
Any clues on what may have caused this issue?

**Comment by niepiekm** [comment]
Hi. After problems with a local pi-hole installation on RPi, I was thinking of replacing it with a cloud installation as well. Then I found this blog post https://taurit.pl/pihole-in-the-cloud-nextdns/ advising to use NextDNS instead of pi-hole in the cloud. So I did and can recommend it. They offer a free tier to use.
