### ISSUE TITLE
How do we enable DoT or DoH?

### ISSUE THREAD

**Issue by Fanboy-Studios** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#7]
**How do we enable DNS over TLS or DNS over HTTPS?**

Currently I'm able to sniff what websites are being attempted to access with packet capture software.

This is maybe preventable with DoT or DoH?
https://blog.cloudflare.com/encrypted-sni/

**Below you can see where I tested access to *explicit site* as I have it blocked on my setup.**
![Wireshark_2020-06-06_11-34-39](https://user-images.githubusercontent.com/13723631/83949588-5cd6fa80-a7ea-11ea-90b0-53435371e94f.png)

**Here you can see my VPN is working, and *explicit site* is blocked.**
![2020-06-06_11-41-35](https://user-images.githubusercontent.com/13723631/83949744-146c0c80-a7eb-11ea-9ebe-a2a54af9cad6.png)

_I am using Cloudflare as my upstream DNS, so ideally something that works with that would be great._

**Also one last thing to note, but not directly related to this project...**

_iOS 13.5.1 currently has a vulnerability where applications are able to bypass VPNs._

You can read about that here:
https://www.forbes.com/sites/zakdoffman/2020/06/04/new-apple-security-blow-ios-1351-hides-a-surprising-problem-for-iphone-users/#3538f8cb2533

**Comment by Fanboy-Studios** [comment]
Also what about obfuscating Wireguard? How would I go about doing that?

Would I need to go full tunnel to hide the information in the queries in the below screenshot?

I use the GCP Always Free Tier, so I don't want to really go full tunnel because of egress charges. 

![Wireshark_2020-06-06_11-56-15](https://user-images.githubusercontent.com/13723631/83949976-dbcd3280-a7ec-11ea-9638-ee855b8d1d26.png)

**Comment by rajannpatel** [comment]
Can you change **Allowed IPs** in the Wireguard configuration on your client device to `0.0.0.0/0`, and repeat your packet sniffing test? Sending all the traffic through Wireguard should make your HTTP requests unreadable - but there is the concern of egress charges. Google Cloud is really only suitable for blocking ads and trackers, because it gets costly to send everything through that.

Obfuscating Wireguard is a challenge I don't know how to solve. It may be worth exploring options like DSVPN, Streisand, Algo, and Outline?
