### ISSUE TITLE
Would it make sense to use a dynamic DNS service?

### ISSUE THREAD

**Issue by Kwbmm** [rajannpatel/Pi-Hole-on-Google-Compute-Engine-Free-Tier-with-Full-Tunnel-and-Split-Tunnel-Wireguard-VPN-Configs#9]
As of now, when creating the VM instance on GCP, we are setting up the VM to have a fixed IP address, so it can always be reached. This IP address has a cost.
If you are not making use of the free tier (for whatever reason), I believe you could save some money by using a dynamic DNS service rather than a fixed IP address.

**Only a small doubt:** The traffic generated by the instance to keep the IP address up to date might go over the price for a fixed IP address, however I believe the traffic generated is very very low.
 
What do you think?

**Comment by rajannpatel** [comment]
I think it's better to use a static IP, always. That said, not everyone has the luxury of doing this. So I'm thinking out loud:

If your server is directly being assigned a public IP address, you can fetch the public IP on demand with this command. There is no network traffic associated with running this command:

```bash
ip addr show dev $(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1) scope global | awk '/inet / {split($
2,var,"/"); print var[1]}'
```

If you are behind a DHCP server, such as a router in your home, or in Google Compute Engine, you will not get your public IP address with the command above. You would instead see the IP address served by your DHCP server. I think the quickest way to get your public IP address is by probing a DNS server:

```bash
dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}'
```

You could store the output of the **dig** command into a text file, and compare the subsequent outputs against the contents of the file. When a change is detected, you could trigger your dynamic DNS software to update the DNS record of a domain you own.

Because DNS updates take time to propagate, when you have an opportunity to use a static IP for your VPN server, you should.
